ColoredWater:
# Больше альфа-канала — выше точность цвета в котле, но менее заметна текстура воды
# По умолчанию: 200 / Макс: 255
# More alpha means more color accuracy but less visible water texture
# Default: 200 / Max: 255
  alpha: 200
# Изначальный цвет воды. Прозрачен, и появляется только при первом изменении цвета
# The initial water color. By default, it is transparent and only appears when the color is changed
  default-color: "#26478a"
ColoredPotionMechanic:
# Возможность заливать в котёл зелья с цветом и брать цветную воду бутылочкой
# The ability to pour potions with a color into a cauldron and take colored water with a bottle
  enabled: true
DyeWaterMechanic:
# Покраска воды в котлах
# Colored water in cauldrons
  enabled: true
  animation:
    enabled: true
    height: 1
    delay: 7
DyeItemsMechanic:
# Возможность красить предметы цветной водой в котле. К примеру: Кожаная броня
# В котле нельзя красить вещи, которые красятся 16 дефолтными цветами. К примеру: Шерсть
# The ability to dye items using colored water in a cauldron. For example, leather armor.
# Items that can only be dyed in 16 colors cannot be dyed in a cauldron. For example: wool.
  enabled: true
Sounds:
  fill-sound: item.bottle.fill
  splash-sound: entity.generic.splash
  emptying-sound: item.bottle.empty